@extends ('client/layout')

@section('content')
<div class="container documents">
    <div style="text-align: center">
        <h3>So without further ado, let's begin!</h3>
        <p>Before beginning, I should probably state that ChooseMyPC takes no liability from damage caused by following this guide. Now that's out of the way...</p>
        <p>First we will be assembling the main components of the PC outside of the case for convenience</p>
        <img class="img-thumbnail" src="{{ URL::asset('image/Assembly/IMG_4853.jpg')}}" width="700" height="467" alt="The motherboard sub-assembly" pagespeed_url_hash="813572309" style="display: inline-block;">
        <h2>Installing the CPU</h2>
        <p>Take the motherboard out of its protective bag and place it on top of its box (a perfect non-conductive workspace which is the right size to fit the motherboard on). Do not place the motherboard on the anti-static bag it was in - although most commonly used designs for bags are not conductive this is not a good work surface and you are better off just using the box as the bag only offers protection when parts are inside of it.</p>
        <img class="img-thumbnail" src="{{ URL::asset('image/Assembly/IMG_4854.jpg')}}" width="700" height="467" alt="Removing the motherboard from the box" pagespeed_url_hash="813572309" style="display: inline-block;">
        <img class="img-thumbnail" src="{{ URL::asset('image/Assembly/IMG_4856.jpg')}}" width="700" height="467" alt="Motherboard on top of its case" pagespeed_url_hash="813572309" style="display: inline-block;">
        <p>Lift the CPU retention bracket lever from underneath its latch by pushing down and out away from the cpu socket. Bear in mind that depending on the socket of your motherboard, this may vary slightly and referring to the manual that came with the motherboard is advisable.</p>
        <img class="img-thumbnail" src="{{ URL::asset('image/Assembly/IMG_4858.jpg')}}" width="700" height="467" alt="The CPU socket" pagespeed_url_hash="813572309" style="display: inline-block;">
        <img class="img-thumbnail" src="{{ URL::asset('image/Assembly/IMG_4867.jpg')}}" width="700" height="467" alt="Unhooking the retention bracket lever" pagespeed_url_hash="813572309" style="display: inline-block;">
        <p>Unbox your CPU at this stage and remove it from the protective moulded plastic, holding it carefully by the edges</p>
        <img class="img-thumbnail" src="{{ URL::asset('image/Assembly/IMG_4869.jpg')}}" width="700" height="467" alt="CPU in plastic" pagespeed_url_hash="813572309" style="display: inline-block;">
        <img class="img-thumbnail" src="{{ URL::asset('image/Assembly/IMG_4870.jpg')}}" width="700" height="467" alt="CPU in plastic" pagespeed_url_hash="813572309" style="display: inline-block;">
        <p>Now proceeds the most nerve racking part of the build. Lift the CPU retention bracket lever to reveal the socket and its pins. These are incredibly delicate and easy to bend (which motherboard manufacturers will not accept an RMA for), so be very careful when working around the socket.</p>
        <img class="img-thumbnail" src="{{ URL::asset('image/Assembly/IMG_4872.jpg')}}" width="700" height="467" alt="Revealing the socket" pagespeed_url_hash="813572309" style="display: inline-block;">
        <p>All CPUs have an arrow in one corner corresponding to an arrow printed on or around a corner of the motherboard socket to indicate which way round it fits. The text on the CPU is also an indication of the 'right way up'. In addition to this, Intel CPUs also have notched sides on the upper left and right edges which match up with the shape of the socket. Gently lower the CPU into the socket in the correct position. You should do this so that the CPU stays as horizontal as you can and makes contact with all pins as close to the same time as possible, however there is obviously some room for error. No force needs to be applied at this stage as this is the job of the retention bracket - the CPU should just fit neatly in its place.</p>
        <img class="img-thumbnail" src="{{ URL::asset('image/Assembly/IMG_4874.jpg')}}" width="700" height="467" alt="Lowering the CPU into place" pagespeed_url_hash="813572309" style="display: inline-block;">
        <img class="img-thumbnail" src="{{ URL::asset('image/Assembly/IMG_4877.jpg')}}" width="700" height="467" alt="CPU in place" pagespeed_url_hash="813572309" style="display: inline-block;">
        <div class="alert alert-warning" role="alert">If your protective plastic socket cover is located on the inside of the retention bracket, you may need to remove the protective plastic cover which was over the socket at this stage. With our motherboard the protective cover is on the outside of the bracket so will pop off when securing the CPU into the socket.</div>
        <p>Gently lower the bracket over the CPU, sliding it onto the raised pillar on the motherboard.</p>
        <img class="img-thumbnail" src="{{ URL::asset('image/Assembly/IMG_4883.jpg')}}" width="700" height="467" alt="Lowering retention bracket" pagespeed_url_hash="813572309" style="display: inline-block;">
        <p>Push down the retention bracket arm and hook it back under the latch where it was originally. This may take some force, and may even cause some rather worrying noises, however if you have placed the CPU in the correct position in the socket no harm will be done and this process ensures that the CPU is in proper contact with the socket. This is an area where more detailed video guides can be watched for reassurance that you are doing the right thing and applying a normal amount of force if you are particularly worried about this step</p>
        <img class="img-thumbnail" src="{{ URL::asset('image/Assembly/IMG_4887.jpg')}}" width="700" height="467" alt="Securing the CPU" pagespeed_url_hash="813572309" style="display: inline-block;">
        <p>The protective cover will pop off as you lower the lever. Be sure to keep this in a safe place, as you will need this if you have to send your motherboard back to the manufacturer to protect the socket during shipping. Your CPU is now installed into the motherboard.</p>
        <img class="img-thumbnail" src="{{ URL::asset('image/Assembly/IMG_4889.jpg')}}" width="700" height="467" alt="CPU in place" pagespeed_url_hash="813572309" style="display: inline-block;">
        <img class="img-thumbnail" src="{{ URL::asset('image/Assembly/IMG_4890.jpg')}}" width="700" height="467" alt="Protective plastic cover" pagespeed_url_hash="813572309" style="display: inline-block;">
        <h2>CPU Cooler Installation</h2>
        <p>If you are using an Intel stock cooler (one which is bundled in the box with the CPU) remove it from the packaging and place the pins in the corners through the holes surrounding the CPU socket (ensuring that the pins at the corners are rotated to an unlocked position by rotating the top of them in the direction of the arrows). After this, turn the top of the pins in the opposite direction to that shown by the arrows to lock it in place. You can check that it is seated correctly by attempting to gently twist it - there should not be any significant movement. Be sure to arrange the fan cable so it doesn’t interfere with the spinning of the fan.</p>
        <div class="alert alert-info" role="alert">If you are using an aftermarket cooler there are a vast array of different mounting mechanisms and so you will need to follow the instructions provided with it ensuring that you use the correct mounting hardware and applying thermal paste as a BB sized ball in the centre of the CPU if necessary. Some CPU coolers, similarly to stock CPU coolers, have thermal paste pre-printed to the underside for easy application (this is frequently the case for closed loop coolers)</div>
        <img class="img-thumbnail" src="{{ URL::asset('image/Assembly/IMG_4892.jpg')}}" width="700" height="467" alt="Applying stock cooler 1" pagespeed_url_hash="813572309" style="display: inline-block;">
        <img class="img-thumbnail" src="{{ URL::asset('image/Assembly/IMG_4893.jpg')}}" width="700" height="467" alt="Applying stock cooler 2" pagespeed_url_hash="813572309" style="display: inline-block;">
        <img class="img-thumbnail" src="{{ URL::asset('image/Assembly/IMG_4898.jpg')}}" width="700" height="467" alt="Applying stock cooler 3" pagespeed_url_hash="813572309" style="display: inline-block;">
        <p>Plug the 4pin PWM fan connector on the end of the wire coming from your CPU fan into the CPU_FAN header on your motherboard at this stage if you wish (we actually forgot about this until the build was already in the case). Watch that the cable isn’t in the way of the fan blade!</p>
        <h2>RAM Installation</h2>
        <p>As the final part of this sub-assembly we will be installing the RAM into the motherboard. Read the motherboard manual to find out which slots you should be using for the number of sticks of RAM you have (they are usually color coded and so can be easily referenced). We will be populating all the slots in our build. First, pull back the clips on either side of the RAM slots you are going to use</p>
        <img class="img-thumbnail" src="{{ URL::asset('image/Assembly/IMG_4906.jpg')}}" width="700" height="467" alt="Pulling back DIMM slot clips" pagespeed_url_hash="813572309" style="display: inline-block;">
        <p>Notice the clear off-centre notch at a point both on the slot and the RAM stick to indicate which way round the sticks should be placed and ensure they can only be placed one way</p>
        <div class="alert alert-danger" role="alert">Note that in the picture below the RAM is being held by the edges. Avoid touching the gold contacts along the bottom edge of the RAM</div>
        <img class="img-thumbnail" src="{{ URL::asset('image/Assembly/IMG_4901.jpg')}}" width="700" height="467" alt="Clearly Notched RAM" pagespeed_url_hash="813572309" style="display: inline-block;">
        <p>Place each RAM stick in a slot and push down evenly on both sides until the clips engage</p>
        <img class="img-thumbnail" src="{{ URL::asset('image/Assembly/IMG_4913.jpg')}}" width="700" height="467" alt="Inserting the RAM" pagespeed_url_hash="813572309" style="display: inline-block;">
        <img class="img-thumbnail" src="{{ URL::asset('image/Assembly/IMG_4918.jpg')}}" width="700" height="467" alt="Pushing the RAM into the slot" pagespeed_url_hash="813572309" style="display: inline-block;">
        <img class="img-thumbnail" src="{{ URL::asset('image/Assembly/IMG_4921.jpg')}}" width="700" height="467" alt="Pushing the RAM into the slot 2" pagespeed_url_hash="813572309" style="display: inline-block;">
        <div class="alert alert-info" role="info">At this point in the build, if you have integrated graphics you can attempt to power on the build outside of the case by connecting the power supply 20/20/24 pin ATX and 4/8pin EPS connectors and shorting out the PW_SWITCH pins on the front panel headers by touching a conductive screwdriver or paperclip to them for a split second or connecting the actual case switch to power the build on.</div>
        <h2>Installing the Motherboard in the Case</h2>
        <p>We can now move this sub-assembly into the case</p>
        <img class="img-thumbnail" src="{{ URL::asset('image/Assembly/IMG_4954.jpg')}}" width="700" height="467" alt="Unboxing" pagespeed_url_hash="813572309" style="display: inline-block;">
        <p>Best part about having a side panel window is peeling this off</p>
        <img class="img-thumbnail" src="{{ URL::asset('image/Assembly/IMG_4962.jpg')}}" width="700" height="467" alt="Mmmmmmmm peeling this stuff off" pagespeed_url_hash="813572309" style="display: inline-block;">
        <p>Take off the case side panels</p>
        <div class="alert alert-info" role="alert">You may need your screwdriver to loosen the thumb screws securing the side panels first of all - they are often very tight from the factory</div>
        <img class="img-thumbnail" src="{{ URL::asset('image/Assembly/IMG_4974.jpg')}}" width="700" height="467" alt="Taking off side panels" pagespeed_url_hash="813572309" style="display: inline-block;">
        <img class="img-thumbnail" src="{{ URL::asset('image/Assembly/IMG_4978.jpg')}}" width="700" height="467" alt="Naked case" pagespeed_url_hash="813572309" style="display: inline-block;">
        <p>Find the box containing your screws and other accessories which are bundled with the case (it is usually located in a 3.5" drive bay) and find the standoffs for your case. These sit between your motherboard and the screw in order to stop the motherboard touching and shorting out on the case and are vitally important. In our case, the standoffs were pre-installed for an ATX motherboard. It is a relatively painless process, if they are not, to go through screwing the standoffs into the case in the locations where your motherboard has a matching hole for a screw.</p>
        <div class="alert alert-danger" role="alert">DO NOT FORGET THE STANDOFFS. To repeat, our case had standoffs pre-installed for an ATX motherboard and so this step was not required. Otherwise you will need to screw the standoffs into the motherboard tray and the screws into that to offset the motherboard from the case and prevent it from shorting out.</div>
        <img class="img-thumbnail" src="{{ URL::asset('image/Assembly/IMG_4980.jpg')}}" width="700" height="467" alt="Accessories box" pagespeed_url_hash="813572309" style="display: inline-block;">
        <img class="img-thumbnail" src="{{ URL::asset('image/Assembly/IMG_4984.jpg')}}" width="700" height="467" alt="What&#39;s inside the box?" pagespeed_url_hash="813572309" style="display: inline-block;">
        <p>Next we need to install the motherboard I/O shield. This is a metal panel which covers the gaps between your motherboard I/O connectors in the cutout at the back of the case. Ensure this is the correct way round (engraved labels facing to the outside of the case and the right way up to match the connectors on the motherboard). This is a time when a lot of builders make their blood sacrifice to their machine on sharp edges, so take care! Place the metal panel into the gap at the back of the case and push firmly around the corners and outside edges until it clicks to secure it.</p>
        <img class="img-thumbnail" src="{{ URL::asset('image/Assembly/IMG_4990.jpg')}}" width="700" height="467" alt="Motherboard i/o shield" pagespeed_url_hash="813572309" style="display: inline-block;">
        <img class="img-thumbnail" src="{{ URL::asset('image/Assembly/IMG_4995.jpg')}}" width="700" height="467" alt="Installation of the i/o shield" pagespeed_url_hash="813572309" style="display: inline-block;">
        <p>Now with standoffs in position and I/O panel placed we can take our motherboard and place it in the case. It is best to lie the case on its side as you do this.</p>
        <p>Lower the motherboard into place. Line up the connectors with the gaps in the I/O panel and push the connectors into the panel before lowering it all the way onto the standoffs. You may need to apply some pressure in the direction of the back of the case to line up the screw holes with the standoffs - this is normal and is the I/O panel resisting the connectors. However be sure that none of the metal tabs from the panel are making contact with the inside of the connectors after the process.</p>
        <img class="img-thumbnail" src="{{ URL::asset('image/Assembly/IMG_4999.jpg')}}" width="700" height="467" alt="Lowering motherboard into the case" pagespeed_url_hash="813572309" style="display: inline-block;">
        <img class="img-thumbnail" src="{{ URL::asset('image/Assembly/IMG_5002.jpg')}}" width="700" height="467" alt="Lining up with the shield" pagespeed_url_hash="813572309" style="display: inline-block;">
        <img class="img-thumbnail" src="{{ URL::asset('image/Assembly/IMG_5003.jpg')}}" width="700" height="467" alt="Pushing the motherboard into place" pagespeed_url_hash="813572309" style="display: inline-block;">
        <p>Find the motherboard screws which were supplied with your case (these usually have a built in washer) and screw them into the standoff, thus securing the motherboard to the case.</p>
        <img class="img-thumbnail" src="{{ URL::asset('image/Assembly/IMG_5006.jpg')}}" width="700" height="467" alt="Finding screw holes" pagespeed_url_hash="813572309" style="display: inline-block;">
        <img class="img-thumbnail" src="{{ URL::asset('image/Assembly/IMG_5012.jpg')}}" width="700" height="467" alt="Screwing in the motherboard" pagespeed_url_hash="813572309" style="display: inline-block;">
        <img class="img-thumbnail" src="{{ URL::asset('image/Assembly/IMG_5018.jpg')}}" width="700" height="467" alt="Screwing in the motherboard 2" pagespeed_url_hash="813572309" style="display: inline-block;">
        <h2>Getting a Start on Cabling</h2>
        <p>Here's the connection of the 4pin connector to the CPU header we left till now!</p>
        <img class="img-thumbnail" src="{{ URL::asset('image/Assembly/IMG_5028.jpg')}}" width="700" height="467" alt="Plugging in the CPU fan connector" pagespeed_url_hash="813572309" style="display: inline-block;">
        <p>While you're connecting fans, you can connect any 3 pin fan headers from case fans to 3 or 4 pin fan headers on the motherboard. See the motherboard manual if you can't find their location. </p>
        <img class="img-thumbnail" src="{{ URL::asset('image/Assembly/IMG_5028.jpg')}}" width="700" height="467" alt="Plugging in the CPU fan connector" pagespeed_url_hash="813572309" style="display: inline-block;">
        <p>Start as you mean to go on with cable management! With a first build it can be tempting to not bother to manage cables and that you will 'sort it out another time' but that way it takes more work later or never gets done - it's very satisfying to have a neat build afterwards, and you can be much more proud of any pictures you show off. It also ensures that cables do not get in the way, gather dust or obstruct airflow. Here we secure the excess cabling of our rear fan with a cable tie.</p>
        <img class="img-thumbnail" src="{{ URL::asset('image/Assembly/IMG_5030.jpg')}}" width="700" height="467" alt="Plugging in the a chassis fan connector" pagespeed_url_hash="813572309" style="display: inline-block;">
        <img class="img-thumbnail" src="{{ URL::asset('image/Assembly/IMG_5032.jpg')}}" width="700" height="467" alt="Plugging in the a chassis fan connector 2" pagespeed_url_hash="813572309" style="display: inline-block;">
        <h2>Adding a Graphics Card</h2>
        <p>Next we can move on to the installation of the graphics card. Remove the PCIe blanking plates corresponding to the slot you will be placing your graphics card in. Again, your motherboard manual will assist you in making a decision about which slot to use, but usually you should use the topmost PCIe x16 slot for your graphics card which more often than not lines up with the second PCIe slot blanking plate (and you will need to take off another below when you are using a usual dual slot graphics card)</p>
        <img class="img-thumbnail" src="{{ URL::asset('image/Assembly/IMG_5039.jpg')}}" width="700" height="467" alt="Unscrewing the blanking slot covers" pagespeed_url_hash="813572309" style="display: inline-block;">
        <img class="img-thumbnail" src="{{ URL::asset('image/Assembly/IMG_5043.jpg')}}" width="700" height="467" alt="Unscrewing the blanking slot covers 2" pagespeed_url_hash="813572309" style="display: inline-block;">
        <p>Press back the clip at the edge of the slot similarly to the RAM slots ready for you to insert the graphics card</p>
        <img class="img-thumbnail" src="{{ URL::asset('image/Assembly/IMG_5049.jpg')}}" width="700" height="467" alt="Releasing PCIe clip" pagespeed_url_hash="813572309" style="display: inline-block;">
        <p>Lower the card into position and push down evenly at both ends until the clip engages.</p>
        <img class="img-thumbnail" src="{{ URL::asset('image/Assembly/IMG_5051.jpg')}}" width="700" height="467" alt="Placing card in slot" pagespeed_url_hash="813572309" style="display: inline-block;">
        <img class="img-thumbnail" src="{{ URL::asset('image/Assembly/IMG_5054.jpg')}}" width="700" height="467" alt="Placed card in slot" pagespeed_url_hash="813572309" style="display: inline-block;">
        <p>Screw the graphics card in to secure it in place - the graphics card will have holes in it similarly to those on the blanking plates allowing you to replace the screws which were originally there. We now have all the major components of the build installed</p>
        <img class="img-thumbnail" src="{{ URL::asset('image/Assembly/IMG_5059.jpg')}}" width="700" height="467" alt="Screwing in the card" pagespeed_url_hash="813572309" style="display: inline-block;">
        <h2>More Cabling - Case Cables</h2>
        <p>Now things get more fiddly as we begin cabling. Our preferred technique is to first sort out front panel connections before moving on to installing the power supply within the case to keep clutter to a minimum</p>
        <img class="img-thumbnail" src="{{ URL::asset('image/Assembly/IMG_5061.jpg')}}" width="700" height="467" alt="Case connections" pagespeed_url_hash="813572309" style="display: inline-block;">
        <p>First we will focus on the front panel header connections which will be separate very small wires such as these, with labels on each for switches and LEDs</p>
        <img class="img-thumbnail" src="{{ URL::asset('image/Assembly/IMG_5063.jpg')}}" width="700" height="467" alt="Front panel connections" pagespeed_url_hash="813572309" style="display: inline-block;">
        <p>Pass them through a case cutout as close to the headers as possible (the front panel header is usually along the bottom row) to the front of the build (we will be hiding cables as much as possible behind the motherboard tray where they are out of sight and do not disrupt airflow)</p>
        <img class="img-thumbnail" src="{{ URL::asset('image/Assembly/IMG_5066.jpg')}}" width="700" height="467" alt="Cable management of front panel connections" pagespeed_url_hash="813572309" style="display: inline-block;">
        <p>We will now be connecting up these cables to the motherboard. This is an area where the motherboard manual is essential as each motherboard has a different arrangement of pins on their front panel header (which is why all the cables are separate rather than being bundled into one larger connector). Some motherboards come with an intermediary connector which does just this, making the job of cabling this header up easier. Double check your positives and negatives on LED connections.</p>
        <img class="img-thumbnail" src="{{ URL::asset('image/Assembly/IMG_5071.jpg')}}" width="700" height="467" alt="Motherboard manual" pagespeed_url_hash="813572309" style="display: inline-block;">
        <img class="img-thumbnail" src="{{ URL::asset('image/Assembly/IMG_5073.jpg')}}" width="700" height="467" alt="Motherboard manual 2" pagespeed_url_hash="813572309" style="display: inline-block;">
        <img class="img-thumbnail" src="{{ URL::asset('image/Assembly/IMG_5075.jpg')}}" width="700" height="467" alt="Connecting the front panel connections" pagespeed_url_hash="813572309" style="display: inline-block;">
        <p>After this tedious job is over you will be pleased to know that all the other cables are relatively simple. If your case has front panel audio connections the next job will be connecting the 'HD Audio' connector to the respective header on the motherboard. This header is, similarly, usually located along the bottom row of the motherboard. Your case may also include an AC97 connector which is legacy and does not need to be connected if a HD Audio connector is present.</p>
        <img class="img-thumbnail" src="{{ URL::asset('image/Assembly/IMG_5086.jpg')}}" width="700" height="467" alt="Connecting HD Audio" pagespeed_url_hash="813572309" style="display: inline-block;">
        <img class="img-thumbnail" src="{{ URL::asset('image/Assembly/IMG_5087.jpg')}}" width="700" height="467" alt="Connecting HD Audio 2" pagespeed_url_hash="813572309" style="display: inline-block;">
        <p>Finally front panel USB 3.0 will be a large connector which is easily distinguishable with two cables coming out of it. Connect this to the header on the motherboard being careful to align the notch carefully so as to plug it in the correct way round.</p>
        <img class="img-thumbnail" src="{{ URL::asset('image/Assembly/IMG_5091.jpg')}}" width="700" height="467" alt="USB 3.0 cable" pagespeed_url_hash="813572309" style="display: inline-block;">
        <img class="img-thumbnail" src="{{ URL::asset('image/Assembly/IMG_5092.jpg')}}" width="700" height="467" alt="Connecting the USB 3.0 cable" pagespeed_url_hash="813572309" style="display: inline-block;">
        <img class="img-thumbnail" src="{{ URL::asset('image/Assembly/IMG_5095.jpg')}}" width="700" height="467" alt="Connecting the USB 3.0 cable 2" pagespeed_url_hash="813572309" style="display: inline-block;">
        <p>With all the case connections dealt with we can now focus on a small amount of cable management before proceeding. For now, just make use of cable ties to group cables together and pull the excess behind the motherboard tray leaving as little cable as possible showing from the front.</p>
        <img class="img-thumbnail" src="{{ URL::asset('image/Assembly/IMG_5099.jpg')}}" width="700" height="467" alt="Cable typing front panel" pagespeed_url_hash="813572309" style="display: inline-block;">
        <img class="img-thumbnail" src="{{ URL::asset('image/Assembly/IMG_5103.jpg')}}" width="700" height="467" alt="Finished job" pagespeed_url_hash="813572309" style="display: inline-block;">
        <h2>Installing the Power Supply</h2>
        <p>Next we will be inserting the power supply. This simply slides into place underneath the motherboard and will sit against the back of the case. Which way up you place the fan really is up to you and what you prefer aesthetically - if you have a case with dust filters at the bottom and your PC is going to be sitting on a hard surface you should consider placing the fan facing downwards to isolate it from the rest of your case airflow. However it is equally valid to place the PSU with the fan facing upwards and this is preferred if your build will be sitting on carpet.</p>
        <img class="img-thumbnail" src="{{ URL::asset('image/Assembly/IMG_5107.jpg')}}" width="700" height="467" alt="PSU Install" pagespeed_url_hash="813572309" style="display: inline-block;">
        <img class="img-thumbnail" src="{{ URL::asset('image/Assembly/IMG_5109.jpg')}}" width="700" height="467" alt="PSU Install 2" pagespeed_url_hash="813572309" style="display: inline-block;">
        <p>The PSU is secured with 4 screws which are supplied with your case in each corner</p>
        <img class="img-thumbnail" src="{{ URL::asset('image/Assembly/IMG_5114.jpg')}}" width="700" height="467" alt="Screwing in the PSU" pagespeed_url_hash="813572309" style="display: inline-block;">
        <h2>Sorting out Power Cabling</h2>
        <p>First take all the connectors straight through the large cutout in the case to the rear of the motherboard tray and pull through all the excess</p>
        <div class="alert alert-info" role="alert">We are using a fully modular power supply which means that all the cables can be removed at the PSU end. If you have a non-modular or semi modular PSU you will have some or all cables which are permanently attached at the PSU end however this is not impactful apart from for cable management. If your PSU is modular in some respect you can see where cables connect at the PSU end using the manual or matching labels on the cables/PSU)</div>
        <img class="img-thumbnail" src="{{ URL::asset('image/Assembly/IMG_5120.jpg')}}" width="700" height="467" alt="PSU cables" pagespeed_url_hash="813572309" style="display: inline-block;">
        <p>Place the 20/24pin ATX power cable and the 4 or 8pin EPS power cable (which is commonly labelled 'CPU Power') back through the cutouts closest to their headers. The EPS power connector will be at the top of your motherboard and 20/24pin cable along the edge. In most cases there is a cutout in the upper left corner of the motherboard to route the 4 or 8pin EPS power cable through in order to reduce cable clutter which you should use, however in our case this was not possible.</p>
        <div class="alert alert-info" role="alert">Cables can be split by manufacturers into multiple components to ensure compatibility with all possible components, such as 4+4 making up an 8 pin EPS connector. You will need to slot together the two sides before inserting it into the full connector if your motherboard uses 8 pin CPU power. Otherwise should use just one half of the connector and leave the other half dangling.</div>
        <div class="alert alert-danger" role="alert">DO NOT plug PCIe connectors into your EPS power connector. This may seem very obvious (8 pin PCIe is differently keyed to 8pin CPU power) but I have seen people connecting a 6 pin PCIe power connector to their 4 pin PCIe power (with 2 pins hanging over the edge). If the number of pins does not match or the connector is impossible to insert for any cable due to keying, it is a safe bet that YOU ARE DOING IT WRONG.</div>
        <img class="img-thumbnail" src="{{ URL::asset('image/Assembly/IMG_5125.jpg')}}" width="700" height="467" alt="24 and 8 pin cables" pagespeed_url_hash="813572309" style="display: inline-block;">
        <img class="img-thumbnail" src="{{ URL::asset('image/Assembly/IMG_5126.jpg')}}" width="700" height="467" alt="Placing through holes in the motherboard tray" pagespeed_url_hash="813572309" style="display: inline-block;">
        <p>Connect the 4 or 8pin EPS power connector to the CPU power connector on the motherboard. This is notched so will only fit one way. Pull any excess cable behind the motherboard tray.</p>
        <img class="img-thumbnail" src="{{ URL::asset('image/Assembly/IMG_5134.jpg')}}" width="700" height="467" alt="Connecting the CPU power" pagespeed_url_hash="813572309" style="display: inline-block;">
        <p>Connect the large 20/24pin cable to its header on the motherboard. You can see which way this connects due to the clip and latch and it is once again notched to ensure it can only be connected one way. Once again keep the excess behind the motherboard tray.</p>
        <img class="img-thumbnail" src="{{ URL::asset('image/Assembly/IMG_5137.jpg')}}" width="700" height="467" alt="Connecting the 24pin power cable" pagespeed_url_hash="813572309" style="display: inline-block;">
        <p>Route any required PCIe connectors for your graphics card through the motherboard backplate cutout closest to the graphics card. All PCIe power connectors on the graphics card must be filled by a cable in order to successfully power the card. 8 pin PCIe power connectors from the PSU are often designed to split into 6 pin and a 2 pin optional part - feel free to use just the 6 pin part if you have a graphics card with a 6 pin connector you need to fill.</p>
        <img class="img-thumbnail" src="{{ URL::asset('image/Assembly/IMG_5127.jpg')}}" width="700" height="467" alt="PCIe power cable" pagespeed_url_hash="813572309" style="display: inline-block;">
        <img class="img-thumbnail" src="{{ URL::asset('image/Assembly/IMG_5128.jpg')}}" width="700" height="467" alt="Placing PCIe cables through holes in the motherboard tray" pagespeed_url_hash="813572309" style="display: inline-block;">
        <p>Insert these cables into the graphics card PCIe connectors which will be located at the side or end of the card.</p>
        <img class="img-thumbnail" src="{{ URL::asset('image/Assembly/IMG_5144.jpg')}}" width="700" height="467" alt="Powering the GPU" pagespeed_url_hash="813572309" style="display: inline-block;">
        <img class="img-thumbnail" src="{{ URL::asset('image/Assembly/IMG_5145.jpg')}}" width="700" height="467" alt="Powering the GPU 2" pagespeed_url_hash="813572309" style="display: inline-block;">
        <p>After this the build is complete and should POST to an error telling you that you have no boot drives connected, if you wish to test it at this point! Don't forget the power switch on the power supply itself and to double check all the above connections if your build shows no signs of life at all.</p>
        <h2>Drive Installation</h2>
        <p>Next you can secure any drives you have to the caddies inside your case. We will simply be installing a single SSD and our case has tool-less drive mounting so we simply slot it into position. Other cases may require inserting drives into caddies using screws or other mechanisms and details of this will be listed in your case manual. SSDs, having no moving parts, can theoretically be placed anywhere in the build including screwed to the back of the motherboard tray to reduce clutter. HDDs will require a proper mounting solution to minimise vibrations.</p>
        <img class="img-thumbnail" src="{{ URL::asset('image/Assembly/IMG_5152.jpg')}}" width="700" height="467" alt="Our SSD" pagespeed_url_hash="813572309" style="display: inline-block;">
        <img class="img-thumbnail" src="{{ URL::asset('image/Assembly/IMG_5154.jpg')}}" width="700" height="467" alt="Our SSD placement" pagespeed_url_hash="813572309" style="display: inline-block;">
        <p>Drives, including optical drives in the 5.25" bay, require two connectors - SATA data and SATA power. Both connectors are "L" shaped so you can take a look before connecting it to see the correct orientation. SATA power can require a moderate amount of pressure to plug into stiff connectors.</p>
        <p>First connect one end of the SATA data cable which will be supplied with your motherboard and/or drive to the drive, and the other to a SATA port on the motherboard. It will usually connect with a satisfying click as the clip engages. You should try to connect to SATA 6gbps (SATA 3) connections on the motherboard when using SSDs to ensure maximum speeds however this will not affect the speed of hard drives and will not impact the real world performance of an SSD significantly if you connect them to SATA 3gbps (SATA 2) interface.</p>
        <img class="img-thumbnail" src="{{ URL::asset('image/Assembly/IMG_5155.jpg')}}" width="700" height="467" alt="SATA data cable" pagespeed_url_hash="813572309" style="display: inline-block;">
        <img class="img-thumbnail" src="{{ URL::asset('image/Assembly/IMG_5156.jpg')}}" width="700" height="467" alt="Connecting the SATA data cable" pagespeed_url_hash="813572309" style="display: inline-block;">
        <p>Next, take a SATA power cable from your PSU and connect it to the SATA power connector on the drive (next to SATA data).</p>
        <img class="img-thumbnail" src="{{ URL::asset('image/Assembly/IMG_5158.jpg')}}" width="700" height="467" alt="SATA power cable" pagespeed_url_hash="813572309" style="display: inline-block;">
        <img class="img-thumbnail" src="{{ URL::asset('image/Assembly/IMG_5160.jpg')}}" width="700" height="467" alt="Connecting the SATA data cable" pagespeed_url_hash="813572309" style="display: inline-block;">
        <h2>Finishing Up</h2>
        <p>Now you are completely finished with building. Only problem is a lot of excess cabling at the rear side of the motherboard tray. Use cable tie points on the case to secure cables out of sight and route them in a channel along the edge of the tray.</p>
        <img class="img-thumbnail" src="{{ URL::asset('image/Assembly/IMG_5168.jpg')}}" width="700" height="467" alt="Cable management" pagespeed_url_hash="813572309" style="display: inline-block;">
        <img class="img-thumbnail" src="{{ URL::asset('image/Assembly/IMG_5172.jpg')}}" width="700" height="467" alt="Cable management 2" pagespeed_url_hash="813572309" style="display: inline-block;">
        <img class="img-thumbnail" src="{{ URL::asset('image/Assembly/IMG_5180.jpg')}}" width="700" height="467" alt="Cable management 3" pagespeed_url_hash="813572309" style="display: inline-block;">
        <img class="img-thumbnail" src="{{ URL::asset('image/Assembly/IMG_5182.jpg')}}" width="700" height="467" alt="Finished back of build" pagespeed_url_hash="813572309" style="display: inline-block;">
        <p>After this you can place the front and back panels back on the PC and you are ready to go! Enjoy your brand new PC and we hope your experience was a positive one.</p>
        <img class="img-thumbnail" src="{{ URL::asset('image/Assembly/IMG_5183.jpg')}}" width="700" height="467" alt="Replacing rear side panel" pagespeed_url_hash="813572309" style="display: inline-block;">
        <img class="img-thumbnail" src="{{ URL::asset('image/Assembly/IMG_5188.jpg')}}" width="700" height="467" alt="Replacing front side panel" pagespeed_url_hash="813572309" style="display: inline-block;">
        <div class="alert alert-success" role="alert">We could have taken more time with this build to neaten up the drive cabling etc, but we ended up with a clean rig with nothing blocking airflow in a relatively short period of time using just a hand full of zip ties in a budget case. We challenge you to beat our cable management!</div>
        <img class="img-thumbnail" src="{{ URL::asset('image/Assembly/IMG_5186.jpg')}}" width="700" height="467" alt="Finished front of build" pagespeed_url_hash="813572309" style="display: inline-block;">
        <img class="img-thumbnail" src="{{ URL::asset('image/Assembly/IMG_5192.jpg')}}" width="700" height="467" alt="All done!" pagespeed_url_hash="813572309" style="display: inline-block;">
        <h3>Have fun building, and thanks for reading!</h3>
    </div>
</div>
@endsection